announcement: ""
cqreceiver:
  ip: 127.0.0.1
  port: 11451
cqsenddest:
  ip: 127.0.0.1
  port: 11451
groupid: "909806523"
livers:
  - nickname: 水姐
    roomId: 6775697
  - nickname: 瑞芙
    roomId: 22470204
  - nickname: 弥希
    roomId: 21672023
  - nickname: 有加
    roomId: 21613353
  - nickname: 清良
    roomId: 22389323
  - nickname: 卡奥斯
    roomId: 22389314
  - nickname: 希亚娜
    roomId: 22608112
  - nickname: 胡桃
    roomId: 4788550
qq: "364551533"
saberchancode: SCT45921Tqj6arbImzDYshqstl5siyKf9
token: ""
waiting: 10
worker_count: 1
workercount: 3
